name: "Setup Fastlane"
description: "Installs Ruby and Fastlane"

runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true  # 💡 automatically runs `bundle install`

    - name: Install Gems
      run: bundle install
      shell: bash