name: Build Unsigned APK

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  use-version:
    uses: ./.github/workflows/get-version-name.yml

  build:
    name: Build Unsigned APK
    runs-on: ubuntu-latest
    needs: use-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Build Unsigned APK
        run: bundle exec fastlane android build_debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-v${{ needs.use-version.outputs.version_name }}
          path: app/build/outputs/apk/debug/app-debug.apk