name: Build Signed APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  use-version:
    uses: ./.github/workflows/get-version-name.yml

  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    needs: use-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Decode and save keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks

      - name: Verify keystore file exists and is readable
        run: |
          if [ -f "app/keystore.jks" ]; then
            echo "Keystore file exists."
            ls -lh app/keystore.jks
            file app/keystore.jks
            realpath app/keystore.jks
          else
            echo "Keystore file NOT found at app/keystore.jks"
            exit 1
          fi

      - name: Build and sign APK
        env:
          KEYSTORE_FILE: /home/runner/work/ScreenSleepTimer/ScreenSleepTimer/app/keystore.jks # dumb f
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          fastlane android build_signed_apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sleeptimer-release-v${{ needs.get-version.outputs.version_name }}
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 7

      - name: Cleanup keystore
        run: rm -f app/keystore.jks 