name: Build Unsigned APK

on:
  workflow_dispatch:

jobs:

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Unsigned APK
        run: bundle exec fastlane android build_unsigned

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk 