name: Get Version Name

on:
  workflow_call:
    outputs:
      version_name:
        description: "The version name extracted from build.gradle.kts"
        value: ${{ jobs.get-version.outputs.version_name }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.version.outputs.version_name }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version name
        id: version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle.kts | sed -E 's/.*versionName = "([^"]+)".*/\1/')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT 